FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["SignalApi.csproj", "."]
RUN dotnet restore "SignalApi.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "SignalApi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "SignalApi.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
EXPOSE 8080
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "SignalApi.dll"]